### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'click.shell_completion'

### ISSUE THREAD

**Issue by felipemontoya** [eduNEXT/tvm#18]
**Describe the bug**
I did a clean install from the current master,

pip install git+https://github.com/eduNEXT/tvm.git

and now if I try to call tvm it fails with:

```
Traceback (most recent call last):
  File "/home/fmo/.local/bin/tvm", line 5, in <module>
    from tvm.cli import main
  File "/home/fmo/.local/lib/python3.8/site-packages/tvm/cli.py", line 19, in <module>
    from click.shell_completion import CompletionItem
ModuleNotFoundError: No module named 'click.shell_completion'
fmo@bmw:~$ which tvm
```

**To Reproduce**

1. pip install git+https://github.com/eduNEXT/tvm.git
2. tvm

**Expected behavior**
The dependencies should be installed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux mint
 
Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma

 - TVM Version: tvm --version also fails

**Comment by felipemontoya** [comment]
I fixed by upgrading my global `click` package to > 8.

pip install click --upgrade  ->  Successfully installed click-8.1.3

**Comment by felipemontoya** [comment]
Is this expected?
