### ISSUE TITLE
[BUG] Error running tvm list command

### ISSUE THREAD

**Issue by felipemontoya** [eduNEXT/tvm#66]
**Describe the bug**
When running `tvm list` the sorting function at https://github.com/eduNEXT/tvm/blob/main/tvm/cli.py#L145 fails because the local_versions are reported as `v13.3.1@my-mango` and this conflicts with the distutils.version.LooseVersion key.

**To Reproduce**
0. Have many installed versions of tutor. 
1. Run `tvm list`
2. See error

```bash
Traceback (most recent call last):
  File "/home/fmo/.local/bin/tvm", line 8, in <module>
    sys.exit(main())
  File "/home/fmo/.local/lib/python3.10/site-packages/tvm/cli.py", line 40, in main
    cli()
  File "/home/fmo/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/fmo/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/fmo/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fmo/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fmo/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/fmo/.local/lib/python3.10/site-packages/tvm/cli.py", line 156, in list_versions
    version_names = sorted(version_names, reverse=False, key=LooseVersion)
  File "/usr/lib/python3.10/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.10/distutils/version.py", line 341, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Expected behavior**
I would expect the list of available versions to show up.

**Desktop (please complete the following information):**
 - OS: linux mint 21.
 - Python 3.8 and 3.10
 - TVM Version: v2.2.0

**Additional context**
This is the current list of installations that I have and that fail.

```
v14.2.2@openai
v14.0.0@tutor
v13.3.1@tvm_env
v13.3.1
v14.0.0@tvm_env
v12.2.0 (active)
v13.2.2
v14.2.2@2022_dec
v12.2.0@openai
v13.0.0@dd_tutor
v13.2.2@GqTXDukMmd
v14.0.0
v12.2.0@nau-lilac
v13.3.1@my-mango
v13.0.0
v14.0.0@tutor2
```

**Comment by JuanDavidBuitrago** [comment]
Hi @felipemontoya,

Thank you for reporting this, we will take it into account to be included in the next sprint that starts on March 6, to be analyzed. If you have any additional comments, feel free to post.

**Comment by Alec4r** [comment]
Ey @felipemontoya I'm working on fix this, but I could not replicate the error:

I tested in:
OS: Mac OS 13.
Python 3.9.6 and 3.10.9
TVM Version: v2.2.0 (Master and Tag)

OS: Ubuntu 22.04
Python 3.10.6
TVM Version: v2.2.0 (Master and Tag)

Also, I created some projects:
- v15.1.0@my-project
- v15.0.0@survey_report
- v15.1.0@olmo

and I don't have problems when I run the command "tvm list".

**Comment by Alec4r** [comment]
@felipemontoya Let me know if you still have problems with this, and if you have more information to I try replicate the error.

**Comment by felipemontoya** [comment]
I know that to solve it, what I did was comment out this line:
https://github.com/eduNEXT/tvm/blob/main/tvm/cli.py#L145

Something about LooseVersion did not want to compare strings to numbers.

We could wrap the line in a try-catch to fix it.

**Comment by felipemontoya** [comment]
However in order to reach that I kinda messed up my dependencies. In the process of fixing that I decided I would rather udpate my linux and delete the ~/.tvm dir.

**Comment by Alec4r** [comment]
I don't want to add an try except just for an isolated case, maybe is just a dependency in your computer so I want to find what is the real problem and not apply a hot fix.

> I know that to solve it, what I did was comment out this line: https://github.com/eduNEXT/tvm/blob/main/tvm/cli.py#L145
> 
> Something about LooseVersion did not want to compare strings to numbers.
> 
> We could wrap the line in a try-catch to fix it.

**Comment by felipemontoya** [comment]
Absolutly. The try catch should be only if we can reproduce the error.

@Alec4r could you run one last test.

try to create a project named with a number. I think the `v14.2.2@2022_dec` might have been the issue. You can take it to the next level by using a number only.

**Comment by felipemontoya** [comment]
It works! I mean, it fails!

Steps to reproduce:

```
tvm project init 2023 v15.3.1
tvm list
```

**Comment by Alec4r** [comment]
> Absolutly. The try catch should be only if we can reproduce the error.
> 
> @Alec4r could you run one last test.
> 
> try to create a project named with a number. I think the `v14.2.2@2022_dec` might have been the issue. You can take it to the next level by using a number only.

I tested in:
OS: Mac OS 13.
Python 3.9.6
TVM Version: v2.2.0 (Master)

with this command `tvm project init 2022_dec v14.2.2`

and I don't have problems
```bash
v14.2.2 (active)
v14.2.2@2022_dec
v14.2.3
v15.0.0
v15.0.0@survey_report
v15.1.0
v15.1.0@my-mango
v15.1.0@olmo
```

**Comment by felipemontoya** [comment]
And its fixed again with `sudo rm -r ~/.tvm/v15.3.1@2023/`

**Comment by felipemontoya** [comment]
> and I don't have problems

Oh wow.

Im running:

```
$ python3 --version
Python 3.10.6

$ tvm --version
tvm, version 2.2.0

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa

```

**Comment by MaferMazu** [comment]
I can't replicate this error.
I'm using Python 3.10.6, TVM 2.2.0, Ubuntu 22.04.2, python3-distutils version 3.10.6-1~22.04, and packaging 21.3 (and I tried with packaging 23.0)
There is something with the packages, but I don't know how to fix this.

**Comment by MaferMazu** [comment]
I don't know what happened these previous two weeks, but the tvm list fails me with the same Felipe's error.

```bash
Traceback (most recent call last):
  File "/home/edunext/.local/bin/tvm", line 8, in <module>
    sys.exit(main())
  File "/home/edunext/.local/lib/python3.10/site-packages/tvm/cli.py", line 40, in main
    cli()
  File "/home/edunext/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/edunext/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/edunext/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/edunext/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/edunext/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/edunext/.local/lib/python3.10/site-packages/tvm/cli.py", line 145, in list_versions
    version_names = sorted(version_names, reverse=False, key=LooseVersion)
  File "/usr/lib/python3.10/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.10/distutils/version.py", line 341, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by Alec4r** [comment]
@felipemontoya @MaferMazu thanks, we are planning add this to our next sprint, so I hope have good news for you soon.

**Comment by MaferMazu** [comment]
I formatted my computer, and I can't replicate this error anymore.

Right now works well, and I have:
- Python3.10
- Click v8.0.3
- Distutils v3.10.6
- Setuptools v59.6.0

Interesting note: starting from Python 3.10, distutils has been declared as deprecated in favor of setuptools.

**Comment by Asespinel** [comment]
I have replicated the error mentioned in this issue on my local environment. Here are the details of my environment settings:
* Python 3.8
* tvm 2.20
* Ubuntu 20.04 LTS
*  Shell: Zsh

**Error details**
1. Create a project with only numbers as a name:
 `tvm project init 2023 v15.0.0 ` 
2. Use `tvm list`
3. Output:
```
Traceback (most recent call last):
  File "/home/andres/.local/bin/tvm", line 8, in <module>
    sys.exit(main())
  File "/home/andres/.local/lib/python3.8/site-packages/tvm/cli.py", line 40, in main
    cli()
  File "/home/andres/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/andres/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/andres/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andres/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andres/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/andres/.local/lib/python3.8/site-packages/tvm/cli.py", line 145, in list_versions
    version_names = sorted(version_names, reverse=False, key=LooseVersion)
  File "/usr/lib/python3.8/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.8/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'

```
**Note:** I previously created a project named '2023-test' with the same tutor version, and I had no issues

**Comment by rediris** [comment]
Still an issue in in `2.2.0`:

```
Traceback (most recent call last):
  File "/some/home/directory/.p3/bin/tvm", line 8, in <module>
    sys.exit(main())
  File "/some/home/directory/.p3/lib/python3.9/site-packages/tvm/cli.py", line 40, in main
    cli()
  File "/some/home/directory/.p3/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/some/home/directory/.p3/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/some/home/directory/.p3/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/some/home/directory/.p3/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/some/home/directory/.p3/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/some/home/directory/.p3/lib/python3.9/site-packages/tvm/cli.py", line 145, in list_versions
    version_names = sorted(version_names, reverse=False, key=LooseVersion)
  File "/some/home/directory/.p3/lib/python3.9/site-packages/setuptools/_distutils/version.py", line 72, in __lt__
    c = self._cmp(other)
  File "/some/home/directory/.p3/lib/python3.9/site-packages/setuptools/_distutils/version.py", line 351, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by bra-i-am** [comment]
hey, I hope you all are doing great. 

I am passing here (sorry for the delay) to inform you that this issue was addressed and the solution involved two main changes:

1. It was removed the dependency `distutils` (which is going to be [deprecated](https://peps.python.org/pep-0632/#migration-advice) in future Python releases) in favor of [`packaging.version`](https://packaging.pypa.io/en/latest/version.html). 
2. It was necessary to modify a sorter function taking into account the [proper way of implementing local version labels](https://peps.python.org/pep-0440/#local-version-identifiers) to allow that `packaging.version` takes the version names properly for creating the Version objects that will be compared for sorting

If you would like more details, please go to the changes applied with PR #68. 

Thank you ✨
